### ISSUE TITLE
老师端上传试卷接口更新

### ISSUE THREAD

**Issue by Tuangtuang** [0GGmr0/ClassTestService#5]
{
    "Papername" :  "影帝的自我修养", 
    "Problemsnum":"20",
    “Single”: [
      {
        Problem: "",
        A:'',
        B:'',
        C:'',
        D:'',
        Answer: ''
      }
    ],
    "Multiple" : [
        {
            Problem: "",
           A:'',
           B:'',
           C:'',
           D:'',
            "Answer" : "ABC"
        }
    ],
    "Judge" : [
        {
            Problem: "",
            A:'',
            B:'',     
        Answer: ''
        }
    ]
}

**Comment by 0GGmr0** [comment]
finish
